import turtle
hai = turtle.Turtle()
hai.shape("turtle")
hai.pensize(10)
hai.color("red")
hai.circle(50)
hai.left(90)
hai.color("green")
hai.circle(50)
hai.color("blue")
hai.left(90)
hai.circle(50)
hai.left(90)
hai.color("yellow")
hai.circle(50)
turtle.done()