print("hello")
print("Tom")
print("---------------------------by Tom----------------------------")
print("                           O")
print("                          /I\\ ")
print("                            /\\")